### ISSUE TITLE
Differentiate between regular season goals and playoff goals

### ISSUE THREAD

**Issue by jasonbosko** [jtmille3/Comp#19]
Goals scored can be skewed by how many games people get in the playoffs, especially with double elimination.  Would be nice to see a breakdown of players' regular season vs playoff goals.

**Comment by jtmille3** [comment]
Can you create a pull request?

**Comment by pip8786** [comment]
I've created the views that will provide the data for this feature.

**Comment by JackOfManyTrades** [comment]
Is this in reference to the Alltime Statistics or the Season Statistics?  Issue #15 covers the Alltime stats but I wasn't sure if this issue was meant for the Season Statistics.  We could do this for Season stats if desired.

**Comment by pip8786** [comment]
I think it would be useful to have on the season stats, we have room next to the names to have 3 columns there (Overall, RS, Playoffs).

**Comment by JackOfManyTrades** [comment]
Implemented in playerstats branch and merged into master in pull request https://github.com/jtmille3/Comp/pull/37
