### ISSUE TITLE
Player Graph Enhancements

### ISSUE THREAD

**Issue by pip8786** [jtmille3/Comp#21]
Add icons for playoffs and league championships to the player graph that you get when you search a player. That way it becomes even more like a summary of the players career. We could also included the playoff vs regular season goals in the graph (maybe a stacked bar graph?)
Also the tooltips for goals when hovering are positioned incorrectly.

**Comment by JackOfManyTrades** [comment]
Related to Issue #15 ?

**Comment by pip8786** [comment]
I think  Jeff was thinking #15 would be in the overall table so you could compare with others.

**Comment by JackOfManyTrades** [comment]
I took a look at this.  The goals tooltip is a problem with the underlying tipsy module.  That code is stale and no longer being maintained.  I can fix this by changing to a simple html title attribute but it's not quite as slick looking.

I took a cut at adding the League and Playoff champion icons to the player graph, placing the appropriate icon close to the season label on the x-axis.  Here's what JM's graph would look like.  If you hover over the icon, it displays title text stating League/Playoff winner the same as the standings display.
![image](https://user-images.githubusercontent.com/45641698/50940877-b4840180-1450-11e9-931a-3754921c137b.png)

I didn't do any research on the season vs playoff goal charting.

**Comment by pip8786** [comment]
I had made views for the playoff vs regular season goals, not sure if they're still in there. I figure we could change this line graph to a stack bar chart maybe to reflect the two categories. 

Your changes look great though if we want to start with just that.

**Comment by JackOfManyTrades** [comment]
I had to refactor the code a bit because I used javascript arrow functions which do not work in IE.  I also added a soccer ball icon to the graph for seasons where the player was the top scorer.  It's smart enough to put the icon on multiple player graphs if there is a tie for the season top scorer.
![image](https://user-images.githubusercontent.com/45641698/51079437-19c83480-1695-11e9-9233-7668debaddb5.png)

**Comment by pip8786** [comment]
Looks good!

**Comment by JackOfManyTrades** [comment]
Stacked bar in place.  Hover text to show total goals (circle at top), playoff goals (top bar), and season goals (bottom bar).  Themed colors to match rest of app.  Also added Trophies, Avg Goals/Season, and Most Goals in 1 Game outside of graph area.  There's not room for much else on that dialog.

![image](https://user-images.githubusercontent.com/45641698/52056175-82d1f800-252f-11e9-90d7-131137597ead.png)

I believe this completes all items identified in this issue, but if there are other ideas, please enter new issues for tracking.

Jack
